### ISSUE TITLE
🚀 [Feature] Frontend: Deeplink to table page

### ISSUE THREAD

**Issue by Mogge** [dreammall-earth/dreammall.earth#1581] opened 2024-07-29 09:56 UTC
## 🚀 Feature

![image](https://github.com/user-attachments/assets/528976cd-9a83-4be4-bd5a-9f524aa52003)

As a user I want to have a deep-link to every table I have access to, e.g. `localhost/table/69` where the number is the id of the table.

If there is no property for the link, then the link must be queried by the table`'s id.

This may also solve some hydration issues.

**Comment by roschaefer** [comment] 2024-07-30 15:52
duplicate of #1007

**Comment by Mogge** [comment] 2024-07-31 08:07
I cannot see this issue as an duplicate. May be it is a part of #1007

**Comment by Bettelstab** [comment] 2024-07-31 10:33
I just had an idea. We often have the situation that the user is given the possibility to share a link so others can join a table. Right now, we would have two different links, one for logged in users and one for guests. That's quite a mental overhead for users and makes user interfaces more complicated.
Instead, could we use one and the same link for both cases? Depending if a user is logged in, he will stay in DreamMall and is shown the table page, or is sent to the /join-table page. (A login option would be nice to have on /join-table, for users which are not logged in but have a DreamMall account.)

**Comment by mahula** [comment] 2024-07-31 10:39
> Right now, we would have two different links, one for logged in users and one for guests.

For clarity of terms:
The two different user types here are _registered_ users (logged in is one possible state of a registered user) and guests (not-registered users)

**Closed** 2024-08-02 10:23 UTC
Labels: feature, service:frontend
