### ISSUE TITLE
🐛 [Bug] Incorrect styling of cockpit sections

### ISSUE THREAD

**Issue by Bettelstab** [dreammall-earth/dreammall.earth#1944] opened 2024-09-04 21:45 UTC
## 🐛 Bug
There is some feedback from @Hardy-Hart-am-Start regarding the styles in the cockpit sections (about me and my tables).

<img width="720" alt="Screenshot 2024-09-04 at 23 20 55" src="https://github.com/user-attachments/assets/25d7c0b0-41d1-4d56-a46a-3868c1e84059">
<img width="382" alt="Screenshot 2024-09-04 at 23 21 04" src="https://github.com/user-attachments/assets/134a9c32-4093-40e3-8198-bc9b10755b8f">
<img width="701" alt="Screenshot 2024-09-04 at 23 21 52" src="https://github.com/user-attachments/assets/dd7ead28-add2-4cce-818c-7136ce3f2a17">
<img width="748" alt="Screenshot 2024-09-04 at 23 22 00" src="https://github.com/user-attachments/assets/32bfa2da-ba3b-4111-baa1-0c3db6c58c51">
<img width="259" alt="Screenshot 2024-09-04 at 23 22 22" src="https://github.com/user-attachments/assets/07e26149-e7a1-4443-91a2-fd8d762d7477">
<img width="491" alt="Screenshot 2024-09-04 at 23 22 27" src="https://github.com/user-attachments/assets/edc786fd-3e46-4421-81ba-0220a32345c4">

**Comment by ulfgebhardt** [comment] 2024-09-16 20:45
Closing this as duplicate of https://github.com/dreammall-earth/dreammall.earth/issues/2168

**Closed by ulfgebhardt** 2024-09-16 20:45 UTC
Labels: bug
