### ISSUE TITLE
🐛 [Bug] Missing Delete-Icon for My Tables

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#1915] opened 2024-09-02 07:08 UTC
## 🐛 Bug

Missing Delete-Icon for My Tables

There is a delete option missing

Current State:
![image](https://github.com/user-attachments/assets/968786ac-8fce-403b-8dca-7dcea930473f)

Figma:
![image](https://github.com/user-attachments/assets/c8fb3ed6-0996-4d7e-96e1-a52a97feff1c)

**Comment by Bettelstab** [comment] 2024-09-02 10:13
Duplicate of https://github.com/dreammall-earth/dreammall.earth/issues/1905

**Closed by Bettelstab** 2024-09-02 10:13 UTC
Labels: bug
