### ISSUE TITLE
🐛 [Bug] Current enrollment-email flow in blueprints is broken

### ISSUE THREAD

**Issue by roschaefer** [dreammall-earth/dreammall.earth#1590] opened 2024-07-31 06:36 UTC
## 🐛 Bug

If you try to run `dreammallearth-enrollment-email` via docker on localhost:

![image](https://github.com/user-attachments/assets/0386fad7-1634-4dc4-90bf-ffb5a8fb05da)

You see this bug:

![image](https://github.com/user-attachments/assets/84ae00d7-131b-4c4d-9384-541c6a08c9e4)

There is a [default email enrollment](https://github.com/goauthentik/authentik/blob/main/blueprints/example/flows-enrollment-email-verification.yaml) flow provided by Authentik.

If you copy this flow into the `dreammall` folder in `authentik/blueprints` (as of now in branch `provision-authentik-with-blueprints`, soon to be merged into `master`) you can find it under "flows" in the Authentik UI.

If you execute this flow you can find the invitation email in mailpit <http://localhost:8025/>.

![image](https://github.com/user-attachments/assets/bbb6f973-36f2-483c-948f-1411106e536a)

![image](https://github.com/user-attachments/assets/f5b82ec4-641d-4367-99aa-90ab8d193c1b)

**Comment by mahula** [comment] 2024-07-31 06:43
> There is a [default email enrollment](https://github.com/goauthentik/authentik/blob/main/blueprints/example/flows-enrollment-email-verification.yaml) flow provided by Authentik.

This flowenrolls the user to Authentik.
The `dreammallearth-enrollment-email` flow needs to be fixed, since this is the flow enrolling users to the DreamMall app

**Comment by mahula** [comment] 2024-08-16 14:50
Using the [current master](https://github.com/dreammall-earth/dreammall.earth/commit/9a44e1dd1c8e582a3b6f73a3d13d1d5bdabf6566) I could not reproduce the described problem.
On a local Linux machine our Authentik signup flow ([dreammallearth-enrollment-email](https://github.com/dreammall-earth/dreammall.earth/blob/master/authentik/blueprints/dreammall/dreammallearth-enrollment-email.yaml)) works as expected.


https://github.com/user-attachments/assets/458e824f-3abe-4e96-969e-58be8750c0a2

**Comment by roschaefer** [comment] 2024-08-19 11:30
> Using the [current master](https://github.com/dreammall-earth/dreammall.earth/commit/9a44e1dd1c8e582a3b6f73a3d13d1d5bdabf6566) I could not reproduce the described problem. On a local Linux machine our Authentik signup flow ([dreammallearth-enrollment-email](https://github.com/dreammall-earth/dreammall.earth/blob/master/authentik/blueprints/dreammall/dreammallearth-enrollment-email.yaml)) works as expected.
> #### How to reproduce
> ##### 1. Run the DreamMall application locally
> 
> Use these commands from our [e2e Github workflow](https://github.com/dreammall-earth/dreammall.earth/blob/master/.github/workflows/e2e.run.tests.yml):
> 
> ```shell
> # in root directory
> docker compose up -d --wait database authentik authentik-worker
> 
> # in backend directory
> cp .env.dist .env && npm install && npm run db:reset && npm run build && npm run start
> 
> # in frontend directory
> rm env.production && cp .env.dist .env && npm install && npm run prod
> 
> # in presenter directory
> rm env.production && cp .env.dist .env && export PORT=3001 && npm install && npm run prod
> 
> # wait until all blueprints have been digested in Authentik
> ```
> 
> ##### 2. Follow the steps in the recording
> reproduce_failing_flow_dreammall-enrollment-email.mp4

I can still reproduce the error locally. Shall we pair-program? @mahula

**Comment by mahula** [comment] 2024-08-28 14:16
Fixed by #1835

**Closed by mahula** 2024-08-28 14:16 UTC
Labels: bug, service:authentik
